// Read viewer/dist/ and generate src/assets.gen.ts
import { readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join, relative, extname } from "node:path";

const VIEWER = "viewer/dist";
const OUT = "src/assets.gen.ts";

const MIME = {
  ".html": "text/html",
  ".js": "application/javascript",
  ".css": "text/css",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".json": "application/json",
};

function walk(dir, list = []) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) walk(p, list);
    else list.push(p);
  }
  return list;
}

const tupa = readFileSync("tupa.dict.yaml", "utf-8");

const files = walk(VIEWER);
const entries = [];

entries.push(`  ["/__tupa.dict.yaml", ${JSON.stringify({ data: tupa, mime: "text/yaml" })}]`);

for (const f of files) {
  const rel = "/" + relative(VIEWER, f).replace(/\\/g, "/");
  const ext = extname(f);
  const mime = MIME[ext] || "application/octet-stream";
  const data = readFileSync(f, "base64");
  entries.push(`  ["${rel}", ${JSON.stringify({ data, mime, b64: true })}]`);
}

const code = `// Auto-generated by scripts/embed-assets.js
export const ASSETS = new Map([
${entries.join(",\n")}
]);
`;

writeFileSync(OUT, code);
console.log(`Embedded ${entries.length} assets → ${OUT}`);
